# Parsing XML and JSON

## Week 2. Practice Programming Assignment 1

In this assignment you are provided with an XML file and JSON file. The files contain some information about stock prices from Moscow Stock Exchange. You will need to inspect the data to answer some questions. 

###### Import coursera grader tools

In [1]:
import tabula
import fitz

<br><br><br><br>

### Part 1. XML

You are provided with file `securities.xml`. Explore it to answer the quesionts.

In [39]:
import xml.etree.ElementTree as ET

In [40]:
input_file = ET.parse('securities.xml')

In [41]:
type(input_file)

xml.etree.ElementTree.ElementTree

In [42]:
root = input_file.getroot()

In [43]:
type(root)

xml.etree.ElementTree.Element

In [44]:
for child in root:
    print(child.tag, child.attrib)

data {'id': 'history'}
data {'id': 'history.cursor'}


In [45]:
answ1 = sum([1 for _ in root.iter("*")])
print(answ1)

88


In [46]:
for child in root.iter("*"):
    print(child.tag, child.attrib)

document {}
data {'id': 'history'}
metadata {}
columns {}
column {'name': 'BOARDID', 'type': 'string', 'bytes': '12', 'max_size': '0'}
column {'name': 'TRADEDATE', 'type': 'date', 'bytes': '10', 'max_size': '0'}
column {'name': 'SHORTNAME', 'type': 'string', 'bytes': '189', 'max_size': '0'}
column {'name': 'SECID', 'type': 'string', 'bytes': '36', 'max_size': '0'}
column {'name': 'NUMTRADES', 'type': 'double'}
column {'name': 'VALUE', 'type': 'double'}
column {'name': 'OPEN', 'type': 'double'}
column {'name': 'LOW', 'type': 'double'}
column {'name': 'HIGH', 'type': 'double'}
column {'name': 'LEGALCLOSEPRICE', 'type': 'double'}
column {'name': 'WAPRICE', 'type': 'double'}
column {'name': 'CLOSE', 'type': 'double'}
column {'name': 'VOLUME', 'type': 'double'}
column {'name': 'MARKETPRICE2', 'type': 'double'}
column {'name': 'MARKETPRICE3', 'type': 'double'}
column {'name': 'ADMITTEDQUOTE', 'type': 'double'}
column {'name': 'MP2VALTRD', 'type': 'double'}
column {'name': 'MARKETPRICE3TRADES

In [47]:
root.tag

'document'

In [48]:
len(root)

2

In [49]:
input_file

In [50]:
for column in input_file.iter('column'):
    print(column.tag, column.attrib)

column {'name': 'BOARDID', 'type': 'string', 'bytes': '12', 'max_size': '0'}
column {'name': 'TRADEDATE', 'type': 'date', 'bytes': '10', 'max_size': '0'}
column {'name': 'SHORTNAME', 'type': 'string', 'bytes': '189', 'max_size': '0'}
column {'name': 'SECID', 'type': 'string', 'bytes': '36', 'max_size': '0'}
column {'name': 'NUMTRADES', 'type': 'double'}
column {'name': 'VALUE', 'type': 'double'}
column {'name': 'OPEN', 'type': 'double'}
column {'name': 'LOW', 'type': 'double'}
column {'name': 'HIGH', 'type': 'double'}
column {'name': 'LEGALCLOSEPRICE', 'type': 'double'}
column {'name': 'WAPRICE', 'type': 'double'}
column {'name': 'CLOSE', 'type': 'double'}
column {'name': 'VOLUME', 'type': 'double'}
column {'name': 'MARKETPRICE2', 'type': 'double'}
column {'name': 'MARKETPRICE3', 'type': 'double'}
column {'name': 'ADMITTEDQUOTE', 'type': 'double'}
column {'name': 'MP2VALTRD', 'type': 'double'}
column {'name': 'MARKETPRICE3TRADESVALUE', 'type': 'double'}
column {'name': 'ADMITTEDVALUE',

**Question 1.** How many elements are in the XML file?

In [172]:
answer_part_1 = 88

<br>

**Question 2.** How many XML elements named 'row' are in the XML-file?

In [52]:
len(input_file.findall('data/rows/row'))

55

In [173]:
answer_part_2 = 55

<br>

**Question 3.** What is the height of the file's XML tree? 

<br>

*Note:* By the height of the tree we mean the length of the longest sequence of nodes from root element to a leaf element. For example: let's look at the following XML:

```
<root>
    <element1>
        <some_element></some_element>
    </element1>
    <element_2></element_2>
</root>
```

The height of the tree here is 3, since there are two sequences from root to leaf:

1. `<root>` - `<element_1>` - `<some_element>`
2. `<root>` - `<element_2>`

The first sequence is the longest, and its length is 3.

In [54]:
def depth_iter(element, tag=None):
    stack = []
    stack.append(iter([element]))
    while stack:
        e = next(stack[-1], None)
        print("e:", e, len(stack) -1)
        if e == None:
            stack.pop()
        else:
            stack.append(iter(e))
            if tag == None or e.tag == tag:
                yield (e, len(stack) - 1)

print(max(map(lambda x: x[1], depth_iter(root))))

e: <Element 'document' at 0x7f3f41429bf0> 0
e: <Element 'data' at 0x7f3f413a06b0> 1
e: <Element 'metadata' at 0x7f3f413a0710> 2
e: <Element 'columns' at 0x7f3f413a0ad0> 3
e: <Element 'column' at 0x7f3f413a0b30> 4
e: None 5
e: <Element 'column' at 0x7f3f413a0b90> 4
e: None 5
e: <Element 'column' at 0x7f3f413a0bf0> 4
e: None 5
e: <Element 'column' at 0x7f3f413a0c50> 4
e: None 5
e: <Element 'column' at 0x7f3f413a0cb0> 4
e: None 5
e: <Element 'column' at 0x7f3f413a0d10> 4
e: None 5
e: <Element 'column' at 0x7f3f413a0d70> 4
e: None 5
e: <Element 'column' at 0x7f3f413a0650> 4
e: None 5
e: <Element 'column' at 0x7f3f413a0050> 4
e: None 5
e: <Element 'column' at 0x7f3f413a00b0> 4
e: None 5
e: <Element 'column' at 0x7f3f413a0110> 4
e: None 5
e: <Element 'column' at 0x7f3f413a0170> 4
e: None 5
e: <Element 'column' at 0x7f3f413a01d0> 4
e: None 5
e: <Element 'column' at 0x7f3f413a0230> 4
e: None 5
e: <Element 'column' at 0x7f3f413a04d0> 4
e: None 5
e: <Element 'column' at 0x7f3f413a0530> 4
e: None

In [174]:
answer_part_3 = 5

<br>

Each `row` element contains data about some stock in its attribute values. For example, attributes CLOSE and OPEN stand for close price and open price for a stock in this day accordingly. Attribute VOLUME stands for total trade volume of the stock in this particular day.

**Question 4.** What is average value of a difference between CLOSE and OPEN prices among all stocks present? 

*Note:* If a stock doesn't have data about its CLOSE and OPEN prices, skip it.

In [78]:
print(root.find("data"))

<Element 'data' at 0x7f3f413a06b0>


In [97]:
dif = []
vol = []
for row in input_file.findall('data[1]/rows/row'):
    if row.attrib["OPEN"] != "" and row.attrib["CLOSE"] != "":
        vol.append(float(row.attrib["VOLUME"]))
        dif.append((float(row.attrib["CLOSE"]) - float(row.attrib["OPEN"])))
        #print(row.attrib["OPEN"], row.attrib["CLOSE"])

print(sum(dif)/len(dif))
print(sum([vol[i]*dif[i] for i in range(len(dif))])/sum(vol))

-81.72016052499997
0.0007582807839039579


In [176]:
answer_part_4 = -81.72016052499997

<br>

**Question 5.** What is the value of largest VOLUME among all stocks present?

In [100]:
int(max(vol))

63615300000

In [177]:
answer_part_5 = 63615300000 #Correct

<br><br><br><br><br>

### Part 2. JSON

You are provided with file `securities.json`. It also has some information about stocks, but It has a slightly different structure. Explore it to answer the quesionts.

*Note:* `data`-element in the file containts rows with data values. To see names for these values (what data value means what) you need to check element `securities['history']['columns']`

<br>

In [102]:
import json
with open("securities.json") as f:
    inp_json = json.load(f)

In [106]:
inp_json

{'history': {'metadata': {'BOARDID': {'type': 'string',
    'bytes': 12,
    'max_size': 0},
   'SECID': {'type': 'string', 'bytes': 36, 'max_size': 0},
   'TRADEDATE': {'type': 'date', 'bytes': 10, 'max_size': 0},
   'SHORTNAME': {'type': 'string', 'bytes': 189, 'max_size': 0},
   'NAME': {'type': 'string', 'bytes': 765, 'max_size': 0},
   'CLOSE': {'type': 'double'},
   'OPEN': {'type': 'double'},
   'HIGH': {'type': 'double'},
   'LOW': {'type': 'double'},
   'VALUE': {'type': 'double'},
   'DURATION': {'type': 'int32'},
   'YIELD': {'type': 'double'},
   'DECIMALS': {'type': 'int32'},
   'CAPITALIZATION': {'type': 'double'},
   'CURRENCYID': {'type': 'string', 'bytes': 9, 'max_size': 0},
   'DIVISOR': {'type': 'double'}},
  'columns': ['BOARDID',
   'SECID',
   'TRADEDATE',
   'SHORTNAME',
   'NAME',
   'CLOSE',
   'OPEN',
   'HIGH',
   'LOW',
   'VALUE',
   'DURATION',
   'YIELD',
   'DECIMALS',
   'CAPITALIZATION',
   'CURRENCYID',
   'DIVISOR'],
  'data': [['RTSI',
    'BPSI',
 

In [105]:
inp_json.keys()
def depth(d):
    if isinstance(d, dict):
        return 1 + (max(map(depth, d.values())) if d else 0)
    return 0

depth(inp_json)

4

In [171]:
def depth2(x):
    if type(x) is dict and x:
        return 1 + max(depth(x[a]) for a in x)
    if type(x) is list and x:
        return 1 + max(depth(a) for a in x)
    return 0

depth2(inp_json)

4



**Question 6.** What is the height of the file's JSON tree? 

*Note:* By the height of the tree we mean the length of the longest sequence of nodes from root element to a leaf element (similar to the height of an XML defined in Question 3)

In [178]:
answer_part_6 = 4 #False
answer_part_6 = 5

<br>

**Question 7.** How many branches does `data` element have?

In [113]:
print(len(inp_json["history"]["data"]), len(inp_json["history"]["data"][0]))

63 16


In [180]:
answer_part_7 = 63

<br>

**Question 8.** What is the average value of a difference between HIGH and LOW prices? 

*Note:* If a stock doesn't have data about its HIGH and LOW prices, skip it.

In [117]:
inp_json["history"].keys()

dict_keys(['metadata', 'columns', 'data'])

In [186]:
print(inp_json["history"]["columns"].index("HIGH"))
print(inp_json["history"]["columns"].index("LOW"))
print(inp_json["history"]["columns"].index("VALUE"))

7
8
9


In [152]:
import numpy as np
x = np.vstack([np.array(inp_json["history"]["data"])[:, 7], np.array(inp_json["history"]["data"])[:, 8], np.array(inp_json["history"]["data"])[:, 9]]).T
x = x.astype("float")
x = x[~np.isnan(x).any(axis=1)]
x

array([[1.31512980e+03, 1.31512980e+03, 0.00000000e+00],
       [8.35257400e+02, 8.35257400e+02, 0.00000000e+00],
       [1.37936000e+03, 1.35794000e+03, 3.39251656e+10],
       [1.48785000e+03, 1.48785000e+03, 0.00000000e+00],
       [1.46900000e+03, 1.46900000e+03, 0.00000000e+00],
       [1.47651000e+03, 1.47651000e+03, 0.00000000e+00],
       [9.45264000e+03, 9.45264000e+03, 0.00000000e+00],
       [9.43827000e+03, 9.43827000e+03, 0.00000000e+00],
       [9.44402000e+03, 9.44402000e+03, 0.00000000e+00],
       [9.78200000e+01, 9.77300000e+01, 2.63430459e+09],
       [9.89400000e+01, 9.88000000e+01, 1.69408478e+09],
       [1.14720000e+02, 1.14690000e+02, 7.08279404e+08],
       [2.23102000e+03, 2.19475000e+03, 2.88867856e+10],
       [1.02310000e+02, 1.02190000e+02, 2.13029172e+09],
       [2.57389000e+03, 2.53349000e+03, 1.38724187e+09],
       [1.88411000e+03, 1.86152000e+03, 3.40853450e+07],
       [4.39544000e+03, 4.35514000e+03, 4.15601780e+08],
       [3.27167000e+03, 3.21143

In [189]:
x[:,0] - x[:,1]

array([0.0000e+00, 0.0000e+00, 2.1420e+01, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 9.0000e-02,
       1.4000e-01, 3.0000e-02, 3.6270e+01, 1.2000e-01, 4.0400e+01,
       2.2590e+01, 4.0300e+01, 6.0240e+01, 1.6397e+02, 6.7530e+01,
       3.1350e+01, 4.4450e+01, 8.4470e+01, 1.1420e+01, 8.2330e+01,
       3.9340e+01, 1.4670e+01, 0.0000e+00, 0.0000e+00, 4.5690e+01,
       1.6900e+00, 5.8500e+00, 7.4200e+00, 6.0700e+00, 2.6930e+01,
       4.6900e+00, 5.9100e+00, 3.4600e+00, 3.2750e+01, 0.0000e+00,
       5.4000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       1.5000e-01, 3.0000e-02, 1.0000e-01, 1.8000e-01, 2.8000e-01,
       6.0000e-02, 1.3000e-01, 1.8000e-01, 0.0000e+00, 0.0000e+00,
       0.0000e+00])

In [156]:
x[:,2]*(x[:,0] - x[:,1])

array([0.00000000e+00, 0.00000000e+00, 7.26677047e+11, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 2.37087413e+08, 2.37171869e+08, 2.12483821e+07,
       1.04772371e+12, 2.55635006e+08, 5.60445716e+10, 7.69987944e+08,
       1.67487517e+10, 1.90470355e+12, 2.66857217e+12, 3.10403960e+10,
       2.55012866e+09, 5.71153323e+10, 1.31836209e+12, 7.17964897e+07,
       2.95135460e+11, 5.22651433e+11, 7.23618672e+09, 0.00000000e+00,
       0.00000000e+00, 2.50366095e+07, 2.53245972e+07, 9.35707500e+05,
       1.37989191e+07, 1.14475319e+09, 1.43539896e+10, 2.21996460e+05,
       2.09989991e+08, 1.03651456e+09, 3.09710433e+10, 0.00000000e+00,
       2.26611000e+05, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 2.54112716e+08, 2.12483821e+07, 2.63430459e+08,
       4.74174825e+08, 4.74343737e+08, 4.24967642e+07, 2.76937923e+08,
       3.83452509e+08, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [155]:
print(np.sum(x[:,0] - x[:,1])/len(x[:,0]))
print(np.sum(x[:,2]*(x[:,0] - x[:,1]))/np.sum(x[:,2]))

16.216071428571432
50.94113419819749


In [194]:
dif = []
for row in inp_json["history"]["data"]:
    if row[7] and row[8] :
        high = float(row[7])
        low = float(row[8])
        dif.append(high-low)
print(dif)
print(sum(dif)/len(dif))

[0.0, 0.0, 21.419999999999845, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0899999999999892, 0.14000000000000057, 0.030000000000001137, 36.26999999999998, 0.12000000000000455, 40.40000000000009, 22.589999999999918, 40.29999999999927, 60.24000000000024, 163.97000000000116, 67.52999999999975, 31.349999999999454, 44.45000000000027, 84.47000000000025, 11.420000000000073, 82.32999999999993, 39.33999999999969, 14.670000000000073, 0.0, 0.0, 45.690000000000055, 1.6899999999999977, 5.850000000000023, 7.4199999999999875, 6.069999999999993, 26.930000000000064, 4.689999999999998, 5.909999999999997, 3.460000000000008, 32.75, 0.0, 5.400000000000006, 0.0, 0.0, 0.0, 0.0, 0.0, 0.14999999999999147, 0.030000000000001137, 0.09999999999999432, 0.18000000000000682, 0.28000000000000114, 0.060000000000002274, 0.12999999999999545, 0.18000000000000682, 0.0, 0.0, 0.0]
15.93157894736842


In [195]:
answer_part_8 = 50.94113419819749   #False
answer_part_8 = 15.93157894736842

<br>

**Question 9.** How many unique values of BOARDID do we see in data?

In [157]:
print(inp_json["history"]["columns"].index("BOARDID"))

0


In [161]:
len(set(np.array(inp_json["history"]["data"])[:, 0]))

2

In [182]:
answer_part_9 = 2 #Correct

<br>

**Question 10.** What value of BOARDID is the most occuring?

In [168]:
uniq = np.unique(np.array(inp_json["history"]["data"])[:, 0], return_counts=True)
uniq

(array(['RTSI', 'SNDX'], dtype=object), array([30, 33]))

In [167]:
result = np.column_stack((uniq[0], uniq[1]))
result

array([['RTSI', 30],
       ['SNDX', 33]], dtype=object)

In [170]:
result[np.argmax(result[:,1]), 0]

'SNDX'

In [183]:
answer_part_10 = "SNDX" #Correct

<br>
<br>

### Submitting answers

In [196]:
print("1:", answer_part_1)
print("2:", answer_part_2)
print("3:", answer_part_3)
print("4:", answer_part_4)
print("5:", answer_part_5)
print("6:", answer_part_6)
print("7:", answer_part_7)
print("8:", answer_part_8)
print("9:", answer_part_9)
print("10:", answer_part_10)

1: 88
2: 55
3: 5
4: -81.72016052499997
5: 63615300000
6: 5
7: 63
8: 15.93157894736842
9: 2
10: SNDX
